
###
GET https://test-api2-73ku.onrender.com/data

###

###
PATCH  https://test-api2-73ku.onrender.com/Footwear/40

Content-Type: application/json
{
   "image": "https://cdn.fcglcdn.com/brainbees/images/products/300x364/11882234a.webp",
    "title": "Pine Kids Lace Up Party Wear Shoes- Black",
    "d-price": 800,
    "original pricer2": 1100,
    "age": "8 - 9Y"
}  